{% set name = "nomad-camels-driver-ni-daq" %}
{% set version = "0.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/nomad_camels_driver_ni_daq-{{ version }}.tar.gz
  sha256: ea057836007f7bcfb2b5066fd0e903dc69b9dd1e0c2193117477df1222e9dcb3

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9.6
    - setuptools >=61.0
    - pip
  run:
    - nidaqmx
    - python >=3.9.6
    - nidaqmx-python

test:
  imports:
    - nomad_camels_driver_ni_daq
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/FAU-LAP/CAMELS_drivers
  summary: This packes provides everything to communicate with a  National Instruments DAQ instrument with NOMAD-CAMELS
  license: LGPL-2.1-or-later
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - jan-janssen
